export * from './base/theory.base';
//export * from './canvas/theory.canvas';
//export * from './directives/theory.directives';
export * from './firebase/theory.firebase';
//export * from './geolocation/theory.geolocation';
//export * from './google/theory.google';
export * from './ionic/theory.ionic';
//export * from './pipes/theory.pipes';
export * from './utility/theory.utility';