import { CollectionKey } from '../enums';
import { CollectionDefinition } from '@theory/firebase/functions';

export const CollectionDefinitions: Record<CollectionKey, CollectionDefinition> = {
    [CollectionKey.Users]: {
        name: CollectionKey.Users,
        version: '1.0.0',
        autoGeneratedId: true
    },

    [CollectionKey.Clusters]: {
        name: CollectionKey.Clusters,
        version: '1.0.0',
        autoGeneratedId: true
    },

    [CollectionKey.Alerts]: {
      name: CollectionKey.Alerts,
      version: '1.0.0',
      autoGeneratedId: true
  }
};
