export enum ActionsUser
{
    Reset  = '[User] Reset',
    Get    = '[User] Get',
    Set    = '[User] Set',
    Patch  = '[User] Patch',
    Save   = '[User] Save',
    Create = '[User] Create',
    Delete = '[User] Delete',

    UserAuthenticate       = '[User] User Authenticate',
    UserAuthenticateCheck  = '[User] User Authenticate Check',
    UserWatch              = '[User] User Watch',
    UserWatchLanguage      = '[User] User Watch Language',
    UserCreate             = '[User] User Create',
    UserAddToken           = '[User] User Add Token',
    LoginEmail             = '[User] Login Email',
    UserLogout             = '[User] User Logout',
    UserSet                = '[User] User Set',
    UserSetClusters        = '[User] User Set Clusters',
    UserSetSubscriptions   = '[User] User Set Subscriptions',
    UserSetStream          = '[User] User Set Stream',
    UserSetAlerts          = '[User] User Set Alerts',
    UserWatchClusters      = '[User] Watch Clusters',
    UserWatchSubscriptions = '[User] Watch Subscriptions',
    UserWatchLocation      = '[User] Watch Location',
    UserWatchStream        = '[User] Watch Stream',
    UserWatchAlerts        = '[User] Alerts Watch',
    UserSubscribe          = '[User] Subscribe',
    UserUnsubscribe        = '[User] Unsubscribe'
}
